[versions]
agp = "8.13.0"
beanshellAndroidLambdaVersion = "3.0.0.beta3"
dexkit = "2.0.7"
androidx-documentfile = "1.1.0"
androidx-annotation = "1.9.1"
kotlinxCoroutinesCore = "1.8.1"
kotlinxCoroutinesAndroid = "1.8.1"
protobufGradlePlugin = "0.9.5"
protobufJavaUtil = "4.32.1"
kotinPlugin = "1.9.25"
compose-bom = "2024.12.01"
composeCompiler = "1.5.15"
androidx-activity = "1.9.3"

[libraries]
beanshell-android-lambda-v300beta3 = { module = "io.github.copylibs:beanshell-android-lambda", version.ref = "beanshellAndroidLambdaVersion" }
dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "androidx-documentfile" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobufJavaUtil" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufGradlePlugin"}
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotinPlugin" }
